#!/usr/bin/env perl
# 
# stats -- provide general statistics functions.
# 
# License - Apache Version 2.0
# Copyright (c) 2017 Arun S Kumar <arunsk.tec@gmail.com>
#
use warnings;
use strict;

# collection of statistics functions
my %stats = (

# expects input to be space separated list of tokens
'mean' => sub {
			my $sum = 0;
			$sum += $_ foreach @_;
			return $sum ? $sum/ @_ : $sum;
		}
);

# run
our $stat = shift;
printf $stats{$stat} ? $stats{$stat}->(@ARGV) . "\n" :
		 "Supported functions are : " .
		  join (q{, }, keys %stats) . "\n";